random_seed: 123

experiment_name: SRDIFF_SIMPLE

# resume_from_checkpoint: ...

sentinel_resolution: "20m"
planetscope_bands: "4b"

train: True
predict: True

model:
  name: srdiff_simple
  channels: 64

datamodule:
  batch_size: 16
  augment: False

trainer:
  max_epochs: 50
  profiler: "simple"
  log_every_n_steps: 1

optimizer:
  lr: 0.0001
  scheduler_step: 1